In [1]:
import numpy as np
import random
import cv2
import os
import matplotlib.pyplot as plt
%matplotlib inline

c:\Users\abdel\.conda\envs\tensorflow\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\abdel\.conda\envs\tensorflow\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\Users\abdel\.conda\envs\tensorflow\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
def seed_everything(seed=42):
    # Random state is steady among the data
    os.environ['PYTHONHASHSEED'] = str(seed)
    random.seed(seed)
    np.random.seed(seed)

def find_indices(array, value):
    return np.where(array == value)[0]

# Read test dataset and the number of elements in each class

In [ ]:
data_test = np.load('Dataset5_raw_test.npz')
image_test, image_label_test = data_test['image'].astype(np.uint8), data_test['image_label'].astype(np.int8)
unique, counts = np.unique(image_label_test, return_counts=True)
counts

array([ 838, 1203, 2039, 1480,  980], dtype=int64)

# Read train and valid dataset and make it balanced

In [3]:
data_train = np.load('Dataset5_raw_train.npz')
image_train, image_label_train = data_train['image'].astype(np.uint8), data_train['image_label'].astype(np.int8)
unique, counts = np.unique(image_label_train, return_counts=True)
counts

array([2512, 3607, 6115, 4438, 2938], dtype=int64)

In [4]:
X_train, y_train = image_train[:2326], image_label_train[:2326]
for i in range(1, 5):
    seed_everything()
    train1_ind = find_indices(image_label_train, i)
    np.random.shuffle(train1_ind)
    X_train = np.concatenate([X_train, image_train[train1_ind[:2326]]])
    y_train = np.concatenate([y_train, image_label_train[train1_ind[:2326]]])

unique, counts = np.unique(y_train, return_counts=True)
counts

array([2326, 2326, 2326, 2326, 2326], dtype=int64)

In [5]:
data_val = np.load('Dataset5_raw_val.npz')
image_val, image_label_val = data_val['image'].astype(np.uint8), data_val['image_label'].astype(np.int8)
unique, counts = np.unique(image_label_val, return_counts=True)
counts

array([ 836, 1202, 2038, 1479,  979], dtype=int64)

In [6]:
X_val, y_val = image_val[:836], image_label_val[:836]
for i in range(1, 5):
    seed_everything()
    val1_ind = find_indices(image_label_val, i)
    np.random.shuffle(val1_ind)
    X_val = np.concatenate([X_val, image_val[val1_ind[:836]]])
    y_val = np.concatenate([y_val, image_label_val[val1_ind[:836]]])
    
unique, counts = np.unique(y_val, return_counts=True)
counts

array([836, 836, 836, 836, 836], dtype=int64)

In [7]:
#Combining
image_total = np.concatenate([X_train, X_val])
label_total = np.concatenate([y_train, y_val])
unique, counts = np.unique(label_total, return_counts=True)
print(counts)
del X_train, X_val, y_train, y_val, image_train, image_label_train, image_val, image_label_val

[3162 3162 3162 3162 3162]


In [8]:
for i in range(0, 5):
    seed_everything()
    val1_ind = find_indices(label_total, i)
    np.random.shuffle(val1_ind)
    if i == 0:
        X_total = image_total[val1_ind[:2616]]
        y_total = label_total[val1_ind[:2616]]
    else:
        X_total = np.concatenate([X_total, image_total[val1_ind[:2616]]])
        y_total = np.concatenate([y_total, label_total[val1_ind[:2616]]])
    
unique, counts = np.unique(y_total, return_counts=True)
counts

array([2616, 2616, 2616, 2616, 2616], dtype=int64)

# Hard Augmentation

In [15]:
import albumentations as A
COUNT_TEST = 1
COUNT = 1
## DO NOT RUN
#### Test dataset resizing only.
# for img, y in zip(image_test, image_label_test):
#   # img = cv2.cvtColor(x, cv2.COLOR_RGB2GRAY)
#   y_str = str(y[0])
#   resizeTransform = A.Compose([A.Resize(height=160, width=160, interpolation=1)], p=1)
#   new_img = resizeTransform(image = img)['image']
#   folder_to_save_img = "Images/Test"
#   name_of_augmented_file = f"{COUNT_TEST}.jpg"
#   cv2.imwrite(f"{folder_to_save_img}/{y_str}/{name_of_augmented_file}", new_img)
#   COUNT_TEST+=1
# print("Done Testing")

for img, y in zip(X_total, y_total): #Imbalanced: image_val, image_label_val, Balanced: X_val, y_val
  y_str = str(y[0])
  for i in range(2):
    resizeTransform = A.Compose([A.Resize(height=224, width=224, interpolation=1)], p=1)
    new_img = resizeTransform(image = img)['image']
    transform = A.Compose([
      A.ImageCompression(quality_lower = 80, quality_upper=100, p=0.7),
      A.GaussNoise(p=0.1),
      A.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.2, always_apply=False, p=0.5),
      A.Flip(p = 0.4),
      A.OneOf([
        A.GaussianBlur(blur_limit=(1,3), sigma_limit=0, p=0.7),
        A.MedianBlur(blur_limit=(1,3), always_apply=False, p=0.3),
      ], p = 0.6),
      A.OneOf([
        A.Rotate(limit=180, interpolation=1, border_mode=4, always_apply=False, p=0.7),
        A.Rotate(limit=180, interpolation=1, border_mode=0, always_apply=False, p=0.3),
      ], p = 0.7),
      A.OneOf([
        A.Affine(scale = 1.4, translate_percent= None,shear = None, p=0.5),
        A.Affine(scale = None,translate_percent= 0.1, shear = None, p=0.25),
        A.Affine(scale = None,translate_percent= None,shear = (10,10), p=0.25), 
      ], p = 0.5),  
    ], 
    p = 0.9)
    aug = transform(image = new_img)["image"] 
    folder_to_save_img = "Images/Hard Aug/Hard_Aug 20-80/Train"
    name_of_augmented_file = f"{COUNT}.jpg"
    if i == 0:
      image_to_save = new_img
    else:
      image_to_save = aug
    cv2.imwrite(f"{folder_to_save_img}/{y_str}/{name_of_augmented_file}", image_to_save)
    COUNT+=1
print("Done T and V")

Done T and V


# Number of elements in each class after the augmentation 

In [16]:
sum = 0
for i in range(5):
    sum = sum + len(os.listdir(f'Images/Hard Aug/Hard_Aug 20-80/Train/{i}'))
    print(f'{i}: ')
    print(len(os.listdir(f'Images/Hard Aug/Hard_Aug 20-80/Train/{i}')))
print(f'total: {sum}')


0: 
3000
1: 
3000
2: 
3000
3: 
3000
4: 
3000
total: 15000
